M48
; DRILL file {KiCad 9.0.3} date 2025-10-26T12:54:48-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-26T12:54:48-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,Plated,3,6,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.150
%
G90
G05
T1
X118.12Y-84.1
X118.12Y-85.2
X118.12Y-87.4
X118.12Y-89.6
X118.12Y-90.7
X118.12Y-91.8
M30
