M48
; DRILL file {KiCad 9.0.3} date 2025-11-22T18:35:35-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-22T18:35:35-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X107.82Y-83.726
X107.82Y-89.506
X167.29Y-79.945
X173.07Y-79.945
M30
